### ISSUE TITLE
A page is never loaded when debt is payed.

### ISSUE THREAD

**Issue by bartvitaly** [20twenty/DebtPlannerTest#10]
When the last payment is made the page does not respond.

Steps:
# As a user or guest open a site
# Create a debt with starting balance 100
# Open the debt
# Make a principal payment of 100 and click Save button

Expected result:
The new principal should be saved and payment progress should be 100%

Actual result:
The page doesn't respond.
http://www.evernote.com/shard/s644/sh/5f73c01e-e77e-4cef-b360-db9d7a1862dd/099fb315e69ca2d78edc495687ee77d5
A control could be obtained after restart of the page.

**Comment by 20twenty** [comment]
fixed
