### ISSUE TITLE
Payoff plan step two has "1 months" in plural

### ISSUE THREAD

**Issue by bartvitaly** [20twenty/DebtPlannerTest#12]
U: User or guest

Steps:
U: Opens site
U: Clicks ""Get Started Now"" button 
U: Opens Create a debt
U: Fills all the required fields
U: Fill 100 into Starting Balance field
U: Fill 49 into Minimum Payment field
U: Fill 0 into APR field
U: Clicks Save button

Expected result:
Step Two section should have "1 month" in singular.

Actual result:
Step Two section has "1 months" in plural.
http://www.evernote.com/shard/s644/sh/d13c13fe-b276-4105-99f8-f772f44b33c7/b5f008d4b3565841519cb0ccf81addad

**Comment by 20twenty** [comment]
fixed issue and updated the test case
